# Generated by Django 3.0.3 on 2021-02-16 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keitech_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='user_name',
        ),
        migrations.AddField(
            model_name='signup',
            name='First_Name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='Last_Name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='Nick_Name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
