# Generated by Django 3.0.3 on 2021-02-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keitech_app', '0002_auto_20210216_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='Phone',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
